@startuml
title JakJak Casino - MVP UML

skinparam classAttributeIconSize 0
top to bottom direction

class Casino {
    - games : List<GameInterface>
    - accountManager : CasinoAccountManager
    + start()
    + playGame()
}

class CasinoAccountManager {
    + createAccount()
    + getAccount()
}

class CasinoAccount {
    - balance : double
    + deposit(amount)
    + withdraw(amount)
    + getBalance()
}

interface GameInterface {
    + setup()
    + play()
    + getRules()
}

interface PlayerInterface {
    + placeBet()
    + getAccount()
}

class CrapsGame {
    +rollDice()
    +isDoubles()
}

class SlotsGame {
    +spinWheel()
    +betIncrement()
}

class RouletteGame {
    +spinWheel()
}

class HorseRaceGame {
    +horseName : String
}

class NumberGuessGame {
   -randomNumber : int
}
class BlackjackGame{
    +hitStay()
    +split()
    +doubleDown()
}


Casino --> CasinoAccountManager
Casino --> GameInterface : runs
CasinoAccountManager --> CasinoAccount : creates

PlayerInterface --> CasinoAccount : uses

GameInterface <|.. SlotsGame
GameInterface <|.. BlackjackGame
GameInterface <|.. CrapsGame
GameInterface <|.. RouletteGame
GameInterface <|.. HorseRaceGame
GameInterface <|.. NumberGuessGame

PlayerInterface <|.. SlotsPlayer
PlayerInterface <|.. BlackjackPlayer
PlayerInterface <|.. CrapsPlayer
PlayerInterface <|.. RoulettePlayer
PlayerInterface <|.. HorseRacePlayer
PlayerInterface <|.. NumberGuessPlayer

SlotsGame *-- SlotsPlayer
BlackjackGame *-- BlackjackPlayer
BlackjackGame *-- DealerPlayer
CrapsGame *-- CrapsPlayer
RouletteGame *-- RoulettePlayer
HorseRaceGame *-- HorseRacePlayer
NumberGuessGame *-- NumberGuessPlayer

BlackjackGame *-- Shoe
Shoe *-- Deck : x decks combined
Deck *-- Card
Card *-- Hand
BlackjackPlayer *-- Hand
DealerPlayer *-- Hand

CrapsGame *-- Die : 2 die

RouletteGame *-- RouletteWheel

SlotsGame *-- SlotMachine

HorseRaceGame *-- RaceHorse



legend left
*--  Composition (owns)
o--  Aggregation (uses)
-->  Association
<|.. Implements
+    Public
-    Private
endlegend

@enduml